modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="coincraft"
version="1.0.0"
displayName="CoinCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="kapla, MCreator"

[[dependencies.coincraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



